---
title: "Resources"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# Data

## Column {data-width="200"}

### Databases

-   [AnyAPI](https://any-api.com/) --- over 1000 public APIs
-   Baldwin Library of Historical [Children's Literature](https://ufdc.ufl.edu/baldwin/all/thumbs) at the University of Florida
-   US [Census](https://www.census.gov/en.html) with [tutorials](https://www.census.gov/data/academy/courses.html)!
-   [Climate Data](https://www.data.gov/climate/) and [NOAA](https://www.ncdc.noaa.gov/cdo-web/datasets)
-   [Diversity in Data](https://data.world/diversityindata)
-   [Education Data Portal](https://educationdata.urban.org/data-explorer/explorer) at the Urban Institute
-   [HealthData.gov](https://healthdata.gov/)
-   [IPEDS](https://nces.ed.gov/ipeds) --- data about universities
-   [Our World in Data](https://github.com/piersyork/owidR) --- R package to access owid data sets
-   [network data](https://github.com/schochastics/networkdata)
- [Protected Planet](https://www.protectedplanet.net/en) --- environmental conservation
-   [Standard eBooks](https://standardebooks.org/) free e-books from the public domain
-   [Stanford GeoSpatial Center](https://github.com/StanfordGeospatialCenter/awesome-public-datasets) --- wide selection of databases
-   [Zurich Open Data](https://data.stadt-zuerich.ch/) --- [in German]

## Column {data-width="200"}

### Data Sets

-   [All the Places](https://www.alltheplaces.xyz/) --- webscraped repository of geodata
-   Anthony [Bourdain travel locations](https://github.com/underthecurve/bourdain-travel-places) --- by Christine Zheng
-   [CNN School Shooting Data](https://github.com/cnnlabs/cnn-school-shooting-data)
-   [Critical Role rolls](https://www.critrolestats.com/)
-   [Data is Plural](https://www.data-is-plural.com/archive/) --- curated weekly
-   [Emancipated slaves](http://www.discoverfreedmen.org/)
-   [FGC](https://data.oneframelink.com/) --- data about fighting games
-   [Gaming dataset repository](https://github.com/leomaurodesenv/game-datasets) by leomaurodesenv
-   [Gender pay gap](https://gender-pay-gap.service.gov.uk/) --- United Kingdom
-   [Gun Violence Archive](https://www.gunviolencearchive.org/)
-   Common Core of Data [high schools (public)](https://nces.ed.gov/ccd/files.asp) and [(private)](https://nces.ed.gov/surveys/pss/)
-   [Hospital prices](https://www.dolthub.com/blog/2021-06-02-hospital-price-v2-retrospective/) --- result of a "bounty"
-   [Human Benchmark](https://humanbenchmark.com/) --- i.e. survey classmates to make simple data sets
- [Human Impacts Database](https://www.anthroponumbers.org/catalog/) --- e.g. carbon footprint
-   [Military capabilities](https://www.militarycapabilities.com/home) --- cPASS (Center for Peace and Security)
-   [Movie posters](https://theposterdb.com/)
-   [NYC Squirrels](https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw)
-   [Sunstroke Epidemic of Cincinnati](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2272406/) --- of 1881
-   [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)
-   [Twitter posts](https://transparency.twitter.com/en/information-operations.html) that are allegedly from state-backed information operations
- [World Population Prospects](https://population.un.org/wpp/) --- from the United Nations

## Column {data-width="200"}

### Data Products

- [Blindspotter](https://ground.news/blindspotter/twitter) --- detect political bias in Twitter accounts
-   [College Scorecard](https://collegescorecard.ed.gov/search/?page=0&sort=median_earnings:desc&toggle=institutions) --- US Dept of Education overview of colleges
- [College Tables](https://collegetables.info/) --- parent organized info to their college-bound teenagers
-   [Defund Data](https://www.defunddata.org/) --- Social Movement Support Lab
-   [EdBuild](https://edbuild.org/) --- "organization that worked to bring common sense and fairness to the way states fund public schools"
- [FBI NIBRS](https://jacobdkaplan.com/nibrs.html) --- by Jacob Kaplan
-   [Gender Pay Gap (UK)](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/articles/findoutthegenderpaygapforyourjob/2016-12-09) --- [quiz](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/articles/testyourknowledgeonthegenderpaygap/2016-12-09), [data](https://gender-pay-gap.service.gov.uk/viewing/download)
- [Gendered Language in Teaching Evaluations](http://benschmidt.org/profGender/#)
- [JWST](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html) --- astronomy data
-   [Know Your Data](https://knowyourdata.withgoogle.com/) --- Google's sample of data sets for Tensor Flow (in beta stage)
-   [Millennials Kill Everything](https://pudding.cool/2019/09/millennials/?fbclid=IwAR12F70S12ipckmziUjIJPsfP3k3PhZfeCLelQCoWiYTfNn2mRjRC4cnU_s) by Alexandra Saizan, Iila Blinderman, and Jan Diehm
-   [Open Secrets](https://www.opensecrets.org/) --- contributions to US politicians
-   [Sundown towns](https://justice.tougaloo.edu/map/)

# Data Science (R)

## Column {data-width="200"}

### Teaching Materials

-   Data Science for [Biological Sciences](https://ds4biomed.tech/index.html) --- bookdown by Daniel Chen (at Virginia Tech)
-   [Data Lab](https://dlab.berkeley.edu/) --- at UC Berkeley ([GitHub](https://github.com/dlab-berkeley))
- From [Data to Viz](https://www.data-to-viz.com/) --- advice on graphing
-   Introduction to R for [Geography and Environmental Science](https://github.com/kristineccles/Introduction_to_R) by Dr. Kristin Eccles
-   [Data4Justice](https://htmlpreview.github.io/?https://github.com/qsideinstitute/Data4Justice-Curriculum/blob/main/Data4Justice-Curriculum-v4.html)
-   Data Science in [Education](https://datascienceineducation.com/) Using R
-   [Engineering Statistics Handbook](https://www.itl.nist.gov/div898/handbook/index.htm) --- by NIST
-   A First Course in [Experimental Design](https://statweb.stanford.edu/~owen/courses/363/doenotes.pdf) --- by Art B Owen (Stanfurd University Stat 263)
-   [history](https://mobile.twitter.com/yohaniddawela/status/1446032040206422019) of R --- by Yohan Iddawela
-   [introverse](https://spielmanlab.github.io/introverse/) --- Stephanie Spielman's tutorials for the `tidyverse`
-   Introduction to [Modern Statistics](https://openintro-ims.netlify.app/) --- by Mine Cetinkaya-Rundel and Jo Hardin
-   [Probability](https://probability4datascience.com/) for Data Science--- by Stanley H Chan
-   Learning [Statistics](https://learningstatisticswithr.com/) with R --- by Danielle Navarro
-   [Sports Data Analysis and Visualization](http://mattwaite.github.io/sports/) --- by Matt Waite
-   [STAT 158](https://csu-r.github.io/Module1/) at Colorado State University (by Alex Fout)
-   [STAT 447](https://stat447.com/) at University of Illinois (by Dirk Eddelbueltel)
-   choosing correct [statistical test](https://stats.oarc.ucla.edu/other/mult-pkg/whatstat/)
-   [StatQuest](https://statquest.org/video-index/) --- videos of statistical concepts
-   Data [Visualization](https://datavizs21.classes.andrewheiss.com/) course --- by Andrew Heiss

### Textbooks

-   [100 free textbooks](https://www.theinsaneapp.com/2020/12/free-data-science-books-pdf.html) --- as of December 2020
- [Advanced R](https://adv-r.hadley.nz/) --- by Hadley Wickham
-   Data Science at the [Command Line](https://www.datascienceatthecommandline.com/) --- by Jeroen Janssens
- Crime by the Numbers: [A Criminologist's Guide to R](https://crimebythenumbers.com/) --- by Jacob Kaplan
-   [Forecasting: Principles and Practice](https://otexts.com/fpp3/) --- by Rob J Hyndman and George Athanasopoulos
-   [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/guides.html) --- by Hadley Wickham
-   Happy Git and [GitHub](https://happygitwithr.com/) for the useR --- by Jenny Bryan and Jim Hester
-   [Python for Data Analysis](https://wesmckinney.com/book/) --- by Wes McKinney
-   [R Cookbook](https://rc2e.com/) --- by James "JD" Long and Paul Teetor
-   [R Graphics Cookbook](https://r-graphics.org/) --- by Winston Chang
-   [R for Data Science](https://r4ds.had.co.nz/?fbclid=IwAR13MM70AcRqpFrhRHWjR4-QO-XURM6Bgy9CitJMsj2I6aF7FhXsOLQPaXM) by Garrett Grolemund and Hadley Wickham
-   Building Web Applications with [Shiny](https://rstudio-education.github.io/shiny-course/) --- by RStudio Education
- Data [Visualization with R](https://rkabacoff.github.io/datavis/) --- by Rob Kabacoff

## Column {data-width="200"}

### Quarto

- [Tip of the Day](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/) --- by Mine Cetinkaya-Rundel

### Tidyverse

-   [encrypt RMD files](https://github.com/dirkschumacher/encryptedRmd) by Dirk Schumacher
-   [style guide](https://style.tidyverse.org/)
-   [tidy evaluation](https://ijlyttle.shinyapps.io/tidyeval/) --- `learnr` app by Ian Lyttle
-   [tutorials](https://www.infoworld.com/article/3411819/do-more-with-r-video-tutorials.html) --- searchable repository
-   [YAML fieldguide](https://ymlthis.r-lib.org/articles/yaml-fieldguide.html)

### Tidy Tuesday

-   [official repository](https://github.com/rfordatascience/tidytuesday)
-   [Palmer Penguins](https://github.com/allisonhorst/palmerpenguins) --- currently accepted example data set ([Spanish](https://mobile.twitter.com/rivaquiroga/status/1295395634934099968))
-   [submissions](https://github.com/jkaupp/tidytuesdays) by Jake Kaupp
-   [tidyrainbow](https://github.com/r-lgbtq/tidyrainbow) will have LGBT data sets

## Column {data-width="200"}

### Shiny

-   [gallery](https://shiny.rstudio.com/gallery/) of examples
-   [Mastering Shiny](https://mastering-shiny.org/) --- [solutions](https://mastering-shiny-solutions.netlify.app/index.html)
-   [RStudio tutorial](https://shiny.rstudio.com/tutorial/) `shiny` tutorial

### utilities

-   [BBC visualization](https://bbc.github.io/rcookbook/) --- how to make data visualizations like the British Broadcasting Corporation
-   [color palettes](https://github.com/EmilHvitfeldt/r-color-palettes/blob/master/type-sorted-palettes.md) --- overview by Emil Hvitfeldt
-   Create stylish tables in R using [formattable](https://www.littlemissdata.com/blog/prettytables) by Little Miss Data
-   [ggplot2 cheatsheets](https://ggplot2tor.com/cheatsheets/) --- by Christian Burkhart
-   [Goblin Notebook](https://help.the-goblin.net/category/how-to-guides/markdown/) --- markdown for TTRPGs
-   [R Seek](https://rseek.org/) --- search tool for R documentation
-   [R Universe](https://r-universe.dev/search/) --- search tool for R packages
-   [regular expression checker](https://regex101.com/)
-   [Tips and tricks for working with images and figures in R Markdown documents](https://www.zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/#arguments-out.width-and-out.height-apply-to-both-existing-images-and-r-generated-figures) by Hollie Olmstead
-   [RStudio webinars](https://www.rstudio.com/resources/webinars/)

# Graphics

## Column {data-width="200"}

### Image Collections

-   [The Flippist](http://www.theflippist.com/)
-   J.G. [Heck](https://www.c82.net/iconography/) --- encyclopedia of illustrations from 1851
-   art of [Paris museums](http://parismuseescollections.paris.fr/fr/recherche/image-libre)
-   infographics by [Plano Informativo](https://planoinformativo.com/grafico)
-   [Roadside America](https://www.flickr.com/photos/library_of_congress/albums/72157686396348231/page1) --- public domain images of points of interest from the rural parts of the United States
- [Vintage Design Inspiration](https://docs.google.com/document/d/12nOKi13zEKF_TK6g6JT8AIQYJnCdHRFLB-s5NK1a1Rw/edit) --- collection of `Flickr` albums by Emma Libbie

## Column {data-width="200"}

### Memes

-   [DrMemes](https://www.drmemes.com/) --- meme generator
-   [The Penske File](https://www.penskefile.com/) --- image finder for Seinfeld

## Column {data-width="200"}

### Reverse Image Search

-   [Google](https://www.google.com/imghp)
-   [TinEye](https://tineye.com/)
-   [Yandex](https://yandex.com/)

### Tools

-   [avatar generator](https://artflow.ai/) --- by artflow
-   [Datawrapper](https://www.datawrapper.de/) --- online tool for data visualization
-   [DrawData](https://drawdata.xyz/) --- draw a graph and then make a CSV!
-   [FlowImmersive](https://flowimmersive.com/) --- commericial product for augmented reality presentations
-   animated [GIF search tool](https://marcosmarp.github.io/GIFinder/) --- by u/marcos_marp
-   [Remove Background](https://www.remove.bg/)
-   [SankeyMATIC](https://sankeymatic.com/) --- make Sankey diagrams
-   [ThisPersonDoesNotExist](https://thispersondoesnotexist.com/) --- GAN-generated fake images of faces
-   [WordArt](https://wordart.com/) --- generate word clouds

# ML (Python)

## Column {data-width="200"}

### Bayesian Approaches

-   [Bayes Camp](http://bayescamp.com/courses)
-   [Bayes Rules!](https://www.bayesrulesbook.com/) --- by Alicia A. Johnson, Miles Q. Ott, Mine Dogucu
-   Bayesian Modeling and Computation in [Python](https://bayesiancomputationbook.com/welcome.html)
-   Monte Carlo [Stan](https://mc-stan.org/)
-   [Statistical Rethinking with brms](https://bookdown.org/content/4857/) --- fan addition to McElreath's book

## Column {data-width="200"}

### Keras

-   [Keras with R](https://blogs.rstudio.com/tensorflow/posts/2019-11-27-gettingstarted-2020/)

### Python

-   [How to Convert any Python File to .EXE](https://www.youtube.com/watch?v=UZX5kH72Yx4)(YouTube) --- includes how to install pip
-   [Learn to Program](https://inventwithpython.com/) --- books by Al Sweigart
-   [pride palettes](https://github.com/cgallinger/pride_palettes) --- by cgallinger for `matplotlib`
-   [regular expression checker](https://pythex.org/)
- [regular expression maker](https://www.autoregex.xyz/) --- English to RegEx with NLP

## Column {data-width="200"}

### Statistics and Modeling

-   [An Introduction to Statistical Learning](https://www.statlearning.com/) --- the best machine learning textbook

    -   [tidymodels labs](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html) --- ISLR labs, but done in `tidymodels` by Emil Hvitfeldt

-   [GAMs in R](https://noamross.github.io/gams-in-r-course/) --- online course by Noam Ross

-   [GLMs in R](https://bookdown.org/roback/bookdown-BeyondMLR/) --- by Paul Roback and Julie Legler

-   [OpenIntro Statistics](https://leanpub.com/openintro-statistics) --- free textbook (suggested donation: \$15)

-   [Physical-Based Deep Learning](http://physicsbaseddeeplearning.org/intro.html)

-   [statistics notes](https://significantstatistics.com/index.php/Graduate_Level:_Intro_to_Probability_and_Statistics) --- at the graduate level

-   free [textbooks and resources in ML](https://mobile.twitter.com/sannykimchi/status/1294285085672431618)

### Learn How to Code

(note: I haven't tried out these sites myself, so I cannot endorse them)

-   [Coding Train](https://thecodingtrain.com/) --- challenges users to build simple games
-   [concept diagrams](https://stanford.edu/~shervine/teaching/cs-221/) --- by Shervine Amidi
-   Dive Into [Deep Learning](https://d2l.ai/index.html) --- interactive lessons
-   [computer science courses with video lectures](https://github.com/Developer-Y/cs-video-courses)
-   [Machine Learning Mastery](https://machinelearningmastery.com/)

# Math

## Column {data-width="200"}

### For Nerds

-   [Alternating harmonic series](https://cindyjs.org/gallery/main/AlternatingSeries/) --- app that shows that rearrangement can sum up to any number
-   [Bernoulli numbers](https://www.bernoulli.org/)---yes, a webpage domain that was registered just for the Bernoulli numbers
-   [Fourier Transformations](https://www.jezzamon.com/fourier/index.html) --- interactive introduction
-   [graph paper](http://www.gridzzly.com/) --- customizable
-   [Ooodle](https://mathszone.co.uk/resources/grid/ooodle/) --- arithmetic version of Wordle
-   [periodic behavior GIF](https://maths-help.tumblr.com/post/57255685488/dassexyattentater-so-this-gif-has-been-going) --- circle, square, and hexagon waves
-   [Pi Day](https://www.idm314.org/) --- International Day of Mathematics

## Column {data-width="200"}

### Textbooks and Materials

-   [Abstract Algebra](http://www.math.clemson.edu/~macaule/classes/f21_math4120/) --- course taught by Dr Matt Macauley
-   [Calculus Made Easy](http://calculusmadeeasy.org/) --- classic textbook from 1910
-   Free [Math textbooks](https://danaernst.com/resources/free-and-open-source-textbooks/) --- Calculus and above
- [Mathigon](https://mathigon.org/) --- polygons and lesson plans
-   [similar triangles](https://mobile.twitter.com/clementinehazel/status/1292292780434358273) --- a quick story for high school Geometry

# Pedagogy

## Column {data-width="200"}

### Activities

-   [Data Nuggets](http://datanuggets.org/)
-   [Drought Center](https://drought.unl.edu/Education/Tutorials.aspx) --- Uni of Nebraska

### Repositories

-   [Inform 7](http://inform7.com/) --- teaches programming through story telling?
-   [TIEE](https://www.esa.org/tiee/index.html) --- Teaching Issues and Experiments in Ecology
-   [Teaching Tech Together](https://teachtogether.tech/) by Greg Wilson --- in particular, check out the tips at the beginning

## Column {data-width="200"}

### Causal Inference

- [Causal Inference](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) --- by Miguel Hernan
- [Causal Inference: The Mixtape](https://mixtape.scunning.com/) --- by Scott Cunningham
- [The Effect](https://theeffectbook.net/) --- by Nick Huntington-Klein [YouTube](https://www.youtube.com/playlist?list=PLcTBLulJV_AK1hKtnO0-kYrU0D09K-kj8)

### Research

-   Evan's Awesome [A/B Tools](https://www.evanmiller.org/ab-testing/) --- sample-size calculator and other tests

-   The [Effect](https://theeffectbook.net/) --- textbook of experiment design by Nick Huntington-Klein
-   [Email extractor](https://email-checker.net/extract)
-   Applied [Empirical Methods](https://github.com/paulgp/applied-methods-phd#lectures-full-syllabus) --- by Paul Goldsmith-Pinkham
-   Flowchart makers: [Draw.io](https://www.draw.io/) and [LucidChart](https://www.lucidchart.com/pages/)
-   [GitHub emojis](https://gist.github.com/rxaviers/7360908)
-   [MaxQDA](https://www.maxqda.com/) --- mixed methods data analysis tool
-   [Papers with Code](https://www.paperswithcode.com/)
-   [Poster printing and templates](https://phdposters.com/)

# Sports

## Column {.tabset}

### Baseball

- Statistics
-   [Baseball Savant](https://baseballsavant.mlb.com/)

- Wild Pitches
- [Sleep Baseball](https://www.sleepbaseball.com/) --- baseball ASMR

- Articles
-   [Attendance in 2019](https://public.tableau.com/views/MajorLeagueBaseballTeamAttendancein2019/MLBAttendance2019?:display_count=y&publish=yes&:origin=viz_share_link&:showVizHome=no)
-   [Like every other industry, the MLB is abandoning Appalachia](https://www.reddit.com/r/baseball/comments/em01kz/essay_like_every_other_industry_the_mlb_is/) --- essay by u/sha256

### general

-   [StatMuse](https://www.statmuse.com/)

# UC Merced

-   UC [Police dashboard](https://police.ucmerced.edu/data-dashboards)
- [Success Anywhere](https://success.ucmerced.edu/) --- overview of campus resources
-   [Teaching Commons](https://teach.ucmerced.edu/)
- [workload estimator](https://cat.wfu.edu/resources/tools/estimator2/) --- WUSTL CETL

# Video Games

## Column {.tabset}

### Starcraft

a recommended order to read the novels

1.  *Heaven's Devils* and *Devils Due*, both good books that tell the story of Raynor and Tychus
2.  *Uprising*, a short story telling how Kerrigan joined the Sons of Korhal
3.  *Liberty's Crusade*, a retelling of the SC1 terran campaign (it's not a great book but a popular one)
4.  *Speed of Darkness*, a retelling of the Battle of Mar Sara from the perspective of a group of marines
5.  *StarCraft: Ghosts: Nova*, the beginning of Nova's story, takes place during the SC1 terran campaign
6.  *Queen of Blades*, a retelling of the SC1 zerg campaign (much better book)
7.  *Shadow of the Xel'Naga*, takes place between SC1 and BW (Seriously though THIS BOOK IS AWFUL AVOID IF POSSIBLE)
8.  *I, Mengsk*, a retelling of the life of Arcturus Mengsk, but takes place right before BW as he recounts his life to Valerian
9.  The Dark Templar Trilogy: Three books that take place after BW, personally my favorite starting point and builds up to SC2
10. *StarCraft Ghosts: Spectres*: The story of the canceled StarCraft Ghosts game, takes place before SC2
11. *Flashpoint*, takes place between Wings of Liberty and Heart of the Swarm ---u/Subsourian

### Stardew Valley

-   [official site](https://www.stardewvalley.net/)
-   [wiki](https://stardewvalleywiki.com/Stardew_Valley_Wiki)
-   [mods](https://www.nexusmods.com/stardewvalley/)

### Super Metroid

-   [DASH Randomizer](https://dashrando.github.io/)
-   [total's Randomizer](https://itemrando.supermetroid.run/)
-   [list of 7 randomizers](https://wiki.supermetroid.run/Randomizers)

### Thronebreaker

-   main thread of [choices](https://www.reddit.com/r/gwent/comments/9ryree/thronebreaker_and_choices_anyone_interested_in/)
-   [Gwent custom card generator](https://custom-gwent.com/) --- for Witcher 3
-   [Gwent custom card generator](https://gwentcard.online/) --- for Gwent Online

Corpse puzzle solution

-   3rd corpse from right on your melee row
-   3rd corpse from right on enemy ranged row \> hero order
-   3rd corpse from right on ranged row
-   4th corpse from right on ranged row to clear the row.
-   4th corpse from right on melee row \> hero order
-   4th corpse from right on melee row to clear the row
-   Anything in middle of enemy melee row to clear as many bodies as possible on melee row. (Sometimes you can full clear this, rng doesn't require it, you should be able to clear enough to guarantee hero order victory regardless next turn)
-   4th corpse from the right on enemy ranged row to clear the row.

Cow Tosser puzzle [solution](https://witcher.fandom.com/wiki/Corrupt_Weapons)

-   Place two Wagenburg on your ranged row.
-   Place a Slinger on the ranged row an hit three Cow Carcass on the same row.
-   Place another Slinger on the ranged row and hit the remaining Cow Carcasses on your battlefield.
-   Use the two Wagenburg order abilities on the opponent's melee and ranged rows.

Fableson puzzle solution

1.  Play Gascon on melee row and attack one of the guards.
2.  Play Reynard on any row and flip a Banquet Table on the melee row (very important).
3.  Play Gascon on the ranged row and push the melee assassin to the ranged row.
4.  Play Reynard on any row and flip a Banquet Table on the ranged row.
5.  Play Gascon on the melee row and attack the injured guard.
6.  (Repeat steps 4-5 until one guard is dead.)
7.  Play Reynard on any row and flip any Banquet Table.
8.  Play Meve for a finishing blow on the healthy guard.

### West of Loathing

-   [DLC guide](https://www.reddit.com/r/westofloathingguide/comments/as9gmx/wol_guide_to_everything_reckonin_at_gun_manor_dlc/) Reddit post
-   [wiki](https://westofloathing.gamepedia.com/West_of_Loathing_Wiki) at Gamepedia
-   [Dirtwater Shopkeepers](https://www.reddit.com/r/westofloathingguide/comments/as8p5a/west_of_loathing_guide_to_everything_dirtwater/) Reddit post
- pale horse can lead to the [ghost ring](https://westofloathing.fandom.com/wiki/Ghost_ring)

Dirtwater Shopkeepers (my preferred order):

1.  Boots (Tony, Fort of Darkness)
2.  Curiousity and Bean (Murray, Lost Dutch Oven Mine)
3.  Leather Goods (Grady, Danny's Tannery)
4.  Bookstore (Alexandria, Alexandria Ranch)
5.  Brewery (Ol' Schmaltz Brewery)
6.  Hot Dog (Doug, Cavern Canyon)

### Wordle

-   [guess helper](https://www.garrickadenbuie.com/blog/wordle-guess-helper/) --- by Garrick Aden-Buie
-   information theory [video 1](https://www.youtube.com/watch?v=v68zYyaEmEA) and [video 2](https://www.youtube.com/watch?v=fRed0Xmc2Wg) --- by 3Blue1Brown

### other games

-   [Baldur's Gate II](https://digiplaygaming.com/baldursgate) --- whole game online??
-   conversation search tool for [Disco Elysium](https://disco-reader.gitlab.io/disco-reader/#/)
-   [fighting game glossary](https://glossary.infil.net/) --- by Infil
-   [Gaming Alexandra](https://www.gamingalexandria.com/wp/) --- video game history and presentation
-   [Old Games Download](https://oldgamesdownload.com/) --- from the '70s, '80s, and '90s
-   [Ori and the Blind Forest randomizer](https://orirando.com/)
-   Simon Tatham's [puzzle games](https://www.chiark.greenend.org.uk/%7Esgtatham/puzzles/)
-   How we see the future of e-sports through the [Street Fighter](https://fugutabetai.com/?postid=615) League --- translation by FutuTabetai
- [Zelda: A Link to the Past](https://github.com/snesrev/zelda3) --- remade in C++

# Bioinformatics

## Column {data-width="200"}

### Covid-19 Dashboards

-   Covid-19 [Conversations](https://covid19conversations.org/webinars) --- webinar series
-   Covid-19 [overview video](https://old.reddit.com/r/educationalgifs/comments/gm064n/an_eli5_breakdown_of_the_covid19_genetic_code/)
-   [Rt](https://rt.live/) --- virus reproduction rate by state
-   Covid [Tracking Project](https://covidtracking.com/)
-   [USA Map](https://covid19usmap.com/)

### Covid-19 Data Sets

-   [Our World in Data](https://github.com/owid/covid-19-data)

## Column {data-width="200"}

### Learning

-   [Bioinformatics Algorithms: An Active Learning Approach](https://www.bioinformaticsalgorithms.org/read-the-book)
-   [John Hopkins Genomics](https://www.coursera.org/specializations/genomic-data-science) --- specialization through Coursera
-   [Rosalind](http://rosalind.info/problems/locations/)--- learning bioinformatics through problem solving
-   [TeSS: Elixer](https://tess.elixir-europe.org/)
-   [UCSD Bioinformatics](https://www.coursera.org/specializations/bioinformatics) --- specialization through Coursera

### Miscellaneous

-   [Black Women in Computational Biology](https://www.blackwomencompbio.org/)
-   [cancer genomic data](https://gdc.cancer.gov/node/31) --- from the National Cancer Institute
-   [ggtree](https://yulab-smu.top/treedata-book/index.html) --- making phylogenetic trees in R
-   [Saccharomyces Genome Database](https://www.yeastgenome.org/downloads) --- yeast genome
-   [Seeq](https://seeq.bio/app/) --- genome search tool

# Cartography

## Column {data-width="200"}

### Spatial Analysis

-   [GeoComputation with R](https://geocompr.robinlovelace.net/) --- by Robin Lovelace
-   [Geographies of Data Exclusion](https://www.oii.ox.ac.uk/research/publications/geographies-of-digital-exclusion-data-and-inequality/) --- by Mark Graham and Martin Dittus
-   [GeoSpatial Health Data](https://www.paulamoraga.com/book-geospatial/) --- by Paula Moraga
- [projection simulation](https://mathigon.org/course/circles/spheres-cones-cylinders#sphere-maps) --- at Mathigon
-   [r-spatial](https://www.r-spatial.org/) blog by Edzer Pebesma
-   [Shade App](https://shademap.app)
-   [spatial genomics](https://spatialgenomics.com/)
- [tidyterra](https://dieghernan.github.io/tidyterra/index.html)

### Spatial Data

- [GeoSeer](https://www.geoseer.net/) --- spatial data search engine
-   [ile de France mobilities](https://data.iledefrance-mobilites.fr/pages/home/) --- French repository
-   [Open Data](https://opendata.apur.org/) --- French repository
-   [Open Street Map](https://www.openstreetmap.org/)
- [Walk Score](https://www.walkscore.com/)
-   [WorldPop]() --- spatial demographics and population dynamics

## Column {data-width="200"}

### Map Makers

-   [CAD Mapper](https://cadmapper.com/)
- [Make My Drive Fun](https://makemydrivefun.com/) --- find roadside attractions
-   [Map Chart](https://mapchart.net/) --- down to state level
-   [Mob Rule](http://mob-rule.com/home) --- down to county level

## Column {data-width="200"}

### Cartographers

-   [pokateomaps](https://www.pokateomaps.com/), [resources](https://docs.google.com/spreadsheets/d/1aLOpW2oQHw5r2vc70o8TiM5SJctR9TuH4a70d-ZtbXA/edit#gid=1329907238)

### Maps

-   [Taste Atlas](https://www.tasteatlas.com/search)

# misc

## Column {data-width="200"}

### Blogs

-   [Airborne Toxic Event](https://theairbornetoxicevent.com/) --- my favorite music group
-   [Amy Gill](http://amygill.net/) --- biomedical scientist
-   [Andrew Geldman](https://statmodeling.stat.columbia.edu/) --- discusses pros and cons of statistics
-   [Catriona Shearer's Geometry Puzzles](https://drive.google.com/file/d/1hVP8tLURVDphmHsphz5BQLVzHCeTts29/view)

### Environment

-   [Kono Designs](http://konodesigns.com/urban-farm/) --- farms inside corporate buildings
-   [wildlife webcams](https://explore.org/livecams)

## Column {data-width="200"}

### Cookbooks and Recipes

-   [Blue Apron](https://www.blueapron.com/cookbook) has all of their recipes online
-   [Budget Bytes](https://www.budgetbytes.com/) --- geared toward low cost-per-serving dishes
-   [Just One Cookbook](https://www.justonecookbook.com/) --- Japanese recipes
-   [Panda Express](https://docs.google.com/document/d/1Swl0i_lmZz18aX11W3zk-gWTRvJMT0fjlchFDVNSi-I/edit) imitation recipes

```{=html}
<!---
# hidden links
* [Online Cooking School](https://www.onlinecookingschool.com/) by America's Test Kitchen
--->
```

### Reddit Favorites

-   [Android animation speed](https://old.reddit.com/r/LifeProTips/comments/d4yqa1/lpt_if_you_have_an_android_phone_go_to_the/)
-   [document all possessions](https://np.reddit.com/r/personalfinance/comments/43iyip/our_family_of_5_lost_everything_in_a_fire/cziljy3/)

```{=html}
<!---
# hidden links

* [Forgotten Employee](https://sites.google.com/site/forgottenemployee/) --- posted by Mr. Moonshine (circa 2002)
* [I also choose this guy's dead wife](https://www.reddit.com/r/AskReddit/comments/5c79n0/comment/d9uf56l?context=1)
* [Reddit Rewind 2018](https://old.reddit.com/r/AskReddit/comments/a4spfa/if_reddit_made_a_reddit_rewind_2018_what_would_be/)

--->
```
## Column {data-width="200"}

### Volunteering

-   [Citizen Science](https://www.citizenscience.gov/)

### miscellaneous

-   [Badger Badger Badger](https://archive.org/details/flash_badger) --- from 2003
-   [Bookshop](https://bookshop.org/) --- support local book stores
-   [bouncing DVD logo](https://www.bouncingdvdlogo.com/) --- popular among fans of The Office
-   Digital [Covid-19 Vaccine Record](https://myvaccinerecord.cdph.ca.gov/)
-   [Hemingway app](https://hemingwayapp.com/) --- describes readability and grade level of writing samples
-   [Kittify](https://kittify.herokuapp.com/) --- translate your text into cat-speak
-   [Radio Garden](http://radio.garden/) --- listen to radio stations from around the world
-   [Rejected Princesses](https://www.rejectedprincesses.com/) --- biographies of lessor known women in history
-   I want to be a [Voice Actor](https://iwanttobeavoiceactor.com/) --- advice for this industry
-   [Wishbook](http://www.wishbookweb.com/the-catalogs/) --- Sears catalogs from 1937 to 1996
